apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080